apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: recipe-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - personalcook
  selector:
    matchLabels:
      app.kubernetes.io/name: recipe_service
      app.kubernetes.io/instance: recipe-service
  endpoints:
    - port: http             
      path: /metrics
      interval: 15s
      scheme: http
