apiVersion: v1
kind: Service
metadata:
  name: recipe-service
  namespace: personalcook
  labels:
    app.kubernetes.io/name: recipe_service
    app.kubernetes.io/instance: recipe-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: recipe_service
    app.kubernetes.io/instance: recipe-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
